name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FC_DEBUG: 1

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn test:unit

  ui-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: |
          sudo apt-get update
          sudo apt-get install -y libasound2t64 fonts-unifont fonts-ubuntu
      - run: npx playwright install chromium
      - run: fc-list
      - run: yarn ci:ui
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-results
          path: test-results/

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install
      - run: yarn typecheck
